# Generated by Django 5.2.3 on 2025-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('button1_text', models.CharField(max_length=50)),
                ('button1_class', models.CharField(default='btn-black', max_length=50)),
                ('button2_text', models.CharField(blank=True, max_length=50)),
                ('button2_class', models.CharField(blank=True, default='btn-white', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
