# Generated by Django 5.2.3 on 2025-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_button', models.BooleanField(default=False)),
                ('button_style', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White')], max_length=10, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
