# Generated by Django 5.2.4 on 2025-07-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_vat',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
