# Generated by Django 5.2.3 on 2025-06-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navbaritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button1_class',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button1_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button2_class',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button2_text',
        ),
        migrations.AddField(
            model_name='slider',
            name='button_class',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
