# Generated by Django 5.2.4 on 2025-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='image',
            field=models.ImageField(blank=True, default='news_images/news.jpg', null=True, upload_to='news_images'),
        ),
    ]
