# Generated by Django 5.2.3 on 2025-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_newsevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='visible_to',
            field=models.CharField(choices=[('all', 'All Users'), ('anonymous', 'Only Anonymous'), ('authenticated', 'Only Logged-in')], default='all', max_length=20),
        ),
    ]
