# Generated by Django 5.2.3 on 2025-06-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_slider_button1_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_class',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue')], max_length=10, null=True),
        ),
    ]
