# Generated by Django 5.2.3 on 2025-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slider_button_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='button_class',
            new_name='button1_class',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='button_text',
            new_name='button1_text',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='button_url',
            new_name='button1_url',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='is_button',
            new_name='is_button1_visible',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='is_visible',
            new_name='is_slide_visible',
        ),
        migrations.AddField(
            model_name='slider',
            name='button2_class',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button2_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button2_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_button2_visible',
            field=models.BooleanField(default=False),
        ),
    ]
