# Generated by Django 5.2.3 on 2025-07-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_navbaritem_visible_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_vat',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
