# Generated by Django 5.2.3 on 2025-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_button_class_slider_button1_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button1_url',
            field=models.CharField(blank=True, help_text="Enter the named URL (e.g., 'home', 'about', 'contact')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button2_url',
            field=models.CharField(blank=True, help_text="Enter the named URL (e.g., 'home', 'about', 'contact')", max_length=255, null=True),
        ),
    ]
