# Generated by Django 5.2.3 on 2025-07-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_size', models.CharField(max_length=20)),
                ('industry_sector', models.CharField(max_length=50)),
                ('business_legal_type', models.CharField(max_length=50)),
                ('business_stage', models.CharField(max_length=50)),
                ('ownership_type', models.CharField(max_length=50)),
                ('registration_certificate', models.FileField(upload_to='certificates/')),
                ('tax_clearance_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='service_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sme_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.smeprofile')),
            ],
        ),
    ]
