# Generated by Django 5.2.3 on 2025-06-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_slider_button1_url_alter_slider_button2_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEDevelopmentStepSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SME Development Steps', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_button_visible', models.BooleanField(default=False)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_class', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue')], max_length=10, null=True)),
                ('button_url', models.CharField(blank=True, help_text="Enter the named URL (e.g., 'home', 'about', 'contact')", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMEDevelopmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_button_visible', models.BooleanField(default=False)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_class', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue')], max_length=10, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.smedevelopmentstepsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
