# Generated by Django 5.2.3 on 2025-07-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smeprofile_serviceoffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='service_description',
            field=models.TextField(default='Not provided.'),
        ),
        migrations.AddField(
            model_name='smeprofile',
            name='service_logo',
            field=models.ImageField(blank=True, null=True, upload_to='service_logos/'),
        ),
        migrations.AddField(
            model_name='smeprofile',
            name='service_name',
            field=models.CharField(default='Not provided.', max_length=100),
        ),
        migrations.AddField(
            model_name='smeprofile',
            name='service_type',
            field=models.CharField(default='Not provided.', max_length=50),
        ),
        migrations.DeleteModel(
            name='ServiceOffered',
        ),
    ]
