# Generated by Django 5.2.3 on 2025-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smedevelopmentstepsection_smedevelopmentstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbaritem',
            old_name='is_visible',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='is_button1_visible',
            new_name='is_button1_active',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='is_button2_visible',
            new_name='is_button2_active',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='is_slide_visible',
            new_name='is_slide_active',
        ),
        migrations.RenameField(
            model_name='smedevelopmentstep',
            old_name='is_visible',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='smedevelopmentstep',
            old_name='is_button_visible',
            new_name='is_button_active',
        ),
        migrations.RenameField(
            model_name='smedevelopmentstepsection',
            old_name='is_visible',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='smedevelopmentstepsection',
            old_name='is_button_visible',
            new_name='is_button_active',
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button1_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button2_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smedevelopmentstep',
            name='button_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smedevelopmentstepsection',
            name='button_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
