# Generated by Django 5.2.3 on 2025-07-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_smeprofile_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
