# Generated by Django 5.2.3 on 2025-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_smeprofile_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='business_legal_type',
            field=models.CharField(choices=[('sole', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='business_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='business_stage',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('early', 'Early Stage'), ('growth', 'Growth'), ('mature', 'Mature')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='industry_sector',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('retail', 'Retail'), ('agriculture', 'Agriculture'), ('healthcare', 'Healthcare'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='ownership_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ngo', 'Non-Profit / NGO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='service_type',
            field=models.CharField(choices=[('consulting', 'Consulting'), ('development', 'Development'), ('marketing', 'Marketing'), ('others', 'Others')], max_length=50),
        ),
    ]
