# Generated by Django 5.2.3 on 2025-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_smeprofile_business_legal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Controls whether the item appears on the left or right of the navbar.', max_length=10),
        ),
    ]
