# Generated by Django 5.2.3 on 2025-07-14 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_navbaritem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDSPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('industry_sector', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('retail', 'Retail'), ('agriculture', 'Agriculture'), ('healthcare', 'Healthcare'), ('others', 'Others')], max_length=50)),
                ('legal_type', models.CharField(choices=[('sole', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation')], max_length=50)),
                ('stage_of_development', models.CharField(choices=[('ideation', 'Ideation'), ('early', 'Early Stage'), ('growth', 'Growth'), ('mature', 'Mature')], max_length=50)),
                ('ownership_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ngo', 'Non-Profit / NGO')], max_length=50)),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('consulting', 'Consulting'), ('development', 'Development'), ('marketing', 'Marketing'), ('others', 'Others')], max_length=50)),
                ('service_description', models.TextField(default='Not provided.')),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='bdsp_service_logos/')),
                ('business_registration_certificate', models.FileField(upload_to='bdsp_certificates/')),
                ('tax_clearance_certificate', models.FileField(blank=True, null=True, upload_to='bdsp_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdsp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
