# Generated by Django 5.2.3 on 2025-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newseventstatus_newseventtype_newsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='publication_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='publication_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
