# Generated by Django 5.2.3 on 2025-07-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bdspprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='required_role',
            field=models.CharField(blank=True, choices=[('sme', 'SME'), ('bdsp', 'BDSP')], help_text='If set, only users with this role can see the item.', max_length=10, null=True),
        ),
    ]
