# Generated by Django 5.2.3 on 2025-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_newsevent_publication_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeguidelinecard',
            name='icon',
            field=models.ImageField(blank=True, default='static\\core\\images\\icons\x01.png', null=True, upload_to='guidelines_icons'),
        ),
    ]
