# Generated by Django 5.2.3 on 2025-06-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_smeguidelinecard_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeguidelinecard',
            name='icon',
            field=models.ImageField(blank=True, default='guidelines_icons\\default.svg', null=True, upload_to='guidelines_icons'),
        ),
    ]
