# Generated by Django 5.2.3 on 2025-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_smeguidelinecard_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='image',
            field=models.ImageField(blank=True, default='news_imagess\\default_news.jpg', null=True, upload_to='news_images/'),
        ),
    ]
