# Generated by Django 5.2.3 on 2025-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_newsevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='image',
            field=models.ImageField(blank=True, default='news_images\\default_news.jpg', null=True, upload_to='news_images/'),
        ),
    ]
