# Generated by Django 5.2.3 on 2025-06-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_newsevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='image',
            field=models.ImageField(blank=True, default='news_images/default_news.jpg', null=True, upload_to='news_images'),
        ),
        migrations.AlterField(
            model_name='smeguidelinecard',
            name='icon',
            field=models.ImageField(blank=True, default='guidelines_icons/default.svg', null=True, upload_to='guidelines_icons'),
        ),
    ]
