# Generated by Django 5.2.3 on 2025-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_newsevent_image_alter_smeguidelinecard_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='smedevelopmentstep',
            name='image',
            field=models.ImageField(blank=True, default='development_steps_images/default_img.jpg', null=True, upload_to='development_steps_images'),
        ),
    ]
