# Generated by Django 5.2.3 on 2025-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_smedevelopmentstep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smedevelopmentstep',
            name='image',
            field=models.ImageField(blank=True, default='development_steps_images/default_img.png', null=True, upload_to='development_steps_images'),
        ),
    ]
