# Generated by Django 5.2.3 on 2025-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_footercontactinfo_footerquicklink_footersocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersocialmedia',
            name='icon',
            field=models.FileField(upload_to='social_icons'),
        ),
    ]
