# Generated by Django 5.2.3 on 2025-06-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_footersocialmedia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercontactinfo',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='footer_icons'),
        ),
    ]
