# Generated by Django 5.2.3 on 2025-06-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_footercontactinfo_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='HeroCarousel',
        ),
    ]
