# Generated by Django 5.2.3 on 2025-06-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_slider_herocarousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocarousel',
            name='is_button1_active',
        ),
        migrations.RemoveField(
            model_name='herocarousel',
            name='is_button2_active',
        ),
    ]
