# Generated by Django 5.2.3 on 2025-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_herocarousel_is_button1_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='button_style',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue')], max_length=10, null=True),
        ),
    ]
