# Generated by Django 5.2.3 on 2025-06-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_navbaritem_button_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smedevelopmentstep',
            name='is_button_active',
        ),
    ]
