# Generated by Django 5.2.3 on 2025-06-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_smedevelopmentstep_is_button_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smedevelopmentstep',
            name='button_class',
        ),
        migrations.RemoveField(
            model_name='smedevelopmentstep',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='smedevelopmentstep',
            name='button_url',
        ),
    ]
