# Generated by Django 5.2.3 on 2025-06-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_notice_noticeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pop_up',
            field=models.BooleanField(default=False),
        ),
    ]
