# Generated by Django 5.2.3 on 2025-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notice_pop_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
