# Generated by Django 5.2.3 on 2025-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cmspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmspage',
            old_name='meta_description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='cmspage',
            old_name='meta_keywords',
            new_name='seo_keywords',
        ),
        migrations.AddField(
            model_name='cmspage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms_images/'),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
