# Generated by Django 5.2.3 on 2025-06-17 09:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_meta_description_cmspage_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='HTML or Markdown content'),
        ),
    ]
