# Generated by Django 5.2.3 on 2025-06-19 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_cmspage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navbaritem'),
        ),
    ]
