# Generated by Django 5.2.3 on 2025-06-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_navbaritem_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbaritem',
            old_name='url',
            new_name='external_url',
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='cms_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cmspage'),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='link_type',
            field=models.CharField(blank=True, choices=[('module', 'Module (Named URL)'), ('cms', 'CMS Page'), ('external', 'External URL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
