# Generated by Django 5.2.3 on 2025-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_url_navbaritem_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
