# Generated by Django 5.2.3 on 2025-06-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_navbaritem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
