# Generated by Django 5.2.3 on 2025-06-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_navbaritem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='cms_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cmspage'),
        ),
    ]
