# Generated by Django 5.2.3 on 2025-06-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_navbaritem_cms_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.navbaritem'),
        ),
    ]
