# Generated by Django 5.2.3 on 2025-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_navbaritem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='popup_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='popup_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
