# Generated by Django 5.2.3 on 2025-06-26 03:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_notice_popup_end_date_notice_popup_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='HTML or Markdown content'),
        ),
    ]
