# Generated by Django 5.2.3 on 2025-06-26 03:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='HTML or Markdown content'),
        ),
    ]
