# Generated by Django 5.2.3 on 2025-06-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_newsevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='image',
            field=models.FileField(blank=True, default='news_images/default_news.jpg', help_text='Upload an image or PDF file', null=True, upload_to='news_images'),
        ),
    ]
