# Generated by Django 5.2.3 on 2025-06-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_newsevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, help_text='Upload an image or PDF file', null=True, upload_to='notices/'),
        ),
    ]
