# Generated by Django 5.2.3 on 2025-07-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_notice_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sme', 'SME'), ('bdsp', 'BDSP')], max_length=10)),
                ('business_name', models.CharField(max_length=255)),
                ('pan_vat', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
